/**
 * Shared types for the PocketSage agent runtime.
 *
 * This module is the single source of truth for every type that crosses the
 * library boundary. Types are grouped by subsystem: messages, models,
 * inference, RAG, skills, the agent loop, and the ExecuTorch bridge.
 */

// ── Messages ──────────────────────────────────────────────────────────────────

/**
 * A single conversation message.
 *
 * The `tool` role carries the result of a tool execution back into the
 * conversation. Tool-result messages must also carry the tool name (`name`) so
 * the model can attribute the result to the right call.
 */
export interface Message {
  /** Who produced this message. */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** The message body. For tool messages this is the serialized tool result. */
  content: string;
  /** Tool call results carry the tool name for context. */
  name?: string;
}

// ── Model ─────────────────────────────────────────────────────────────────────

/**
 * Model speed tier. `fast` maps to Llama 3.2 1B, `balanced` to Llama 3.2 3B.
 *
 * The tier is what the inference layer uses to select which model to load;
 * use {@link ModelInfo.id} when you need a specific model.
 */
export type ModelTier = 'fast' | 'balanced';

/**
 * Static metadata describing a model that can be downloaded and run on device.
 */
export interface ModelInfo {
  /** Stable identifier, e.g. `llama-3.2-1b-spinquant`. */
  id: string;
  /** Human-readable display name. */
  name: string;
  /** Which speed tier this model satisfies. */
  tier: ModelTier;
  /** Parameter count as a label, e.g. "1B". */
  parameterCount: string;
  /** Quantization scheme, e.g. "SpinQuant". */
  quantization: string;
  /** Size of the model file on disk, in bytes. */
  sizeBytes: number;
  /** Maximum context length in tokens. */
  contextWindow: number;
  /** Minimum device RAM required to run the model, in bytes. */
  minRamBytes: number;
  /** Remote URL of the `.pte` model binary. */
  downloadUrl: string;
  /** Remote URL of the tokenizer JSON. */
  tokenizerUrl: string;
  /** Remote URL of the tokenizer config JSON. */
  tokenizerConfigUrl: string;
  /** SHA-256 of the model binary, hex-encoded. */
  sha256: string;
  /** Model license, e.g. "Llama 3.2 Community License". */
  license: string;
}

/**
 * Download state of a model, tracked by {@link ModelManager}.
 *
 * - `not_downloaded` — nothing on disk yet.
 * - `downloading` — a download is in flight; `progress` is 0–1.
 * - `downloaded` — all resources are on disk and verified.
 * - `error` — the last attempt failed; `message` explains why.
 */
export type ModelDownloadState =
  | { status: 'not_downloaded' }
  | { status: 'downloading'; progress: number } // 0–1
  | { status: 'downloaded' }
  | { status: 'error'; message: string };

// ── Inference ─────────────────────────────────────────────────────────────────

/**
 * Declarative tool definition offered to the model in the system prompt.
 */
export interface ToolDefinition {
  /** Fully-qualified tool name, e.g. `calendar.list`. */
  name: string;
  /** Plain-language description of what the tool does. */
  description: string;
  /** JSON-Schema-style parameter declaration. */
  parameters: {
    type: 'object';
    properties: Record<
      string,
      {
        type: string;
        description: string;
        enum?: string[];
      }
    >;
    required: string[];
  };
}

/**
 * A tool invocation parsed from the model's raw output.
 *
 * The parser generates `id` — the model does not supply one.
 */
export interface ToolCall {
  /** Unique id generated by the parser. */
  id: string;
  /** Tool name, e.g. `calendar.list`. */
  name: string;
  /** Arguments extracted from the model output. */
  arguments: Record<string, unknown>;
}

/**
 * The outcome of executing a {@link ToolCall}.
 */
export interface ToolResult {
  /** The id of the call this result answers. */
  toolCallId: string;
  /** Whatever the tool returned. */
  result: unknown;
  /** Set when the tool threw; `result` is then unreliable. */
  error?: string;
}

/**
 * Why a generation ended.
 *
 * - `stop` — the model finished normally.
 * - `tool-calls` — the model emitted tool calls instead of a final answer.
 * - `length` — the output reached the configured `maxTokens` limit.
 * - `error` — generation failed or was aborted.
 */
export type FinishReason = 'stop' | 'tool-calls' | 'length' | 'error';

/**
 * The complete result of one generation call.
 */
export interface GenerationResult {
  /** Raw text produced by the model (may include tool-call JSON). */
  text: string;
  /** Why generation ended. */
  finishReason: FinishReason;
  /** Tool calls parsed from `text` (empty when `finishReason` is not `tool-calls`). */
  toolCalls: ToolCall[];
  /** Token usage (exact when the native module reports it, estimated otherwise). */
  usage: { promptTokens: number; completionTokens: number };
}

/**
 * Callbacks for streaming generation and agent-loop progress.
 */
export interface StreamCallbacks {
  /** Called for every token batch. `accumulatedText` is the full text so far. */
  onToken: (token: string, accumulatedText: string) => void;
  /** Called when a tool call is discovered in the model output. */
  onToolCall?: (toolCall: ToolCall) => void;
  /** Called when generation finishes with the final result. */
  onComplete?: (result: GenerationResult) => void;
  /** Called when generation fails. */
  onError?: (error: Error) => void;
}

// ── RAG ────────────────────────────────────────────────────────────────────────

/**
 * Options controlling how text is split into chunks for embedding.
 */
export interface ChunkOptions {
  /** Maximum chunk length in characters (default 500). */
  maxChunkSize: number;
  /** Overlap between adjacent chunks in characters (default 50). */
  overlap: number;
}

/**
 * A single stored vector with its source text.
 */
export interface VectorEntry {
  /** Stable entry id. */
  id: string;
  /** Original text the vector was embedded from. */
  text: string;
  /** Embedding vector. */
  vector: number[];
  /** Arbitrary caller metadata. */
  metadata?: Record<string, unknown>;
}

/**
 * A ranked match from a vector search.
 */
export interface SearchResult {
  /** The matched entry. */
  entry: VectorEntry;
  /** Cosine similarity, 0–1. */
  score: number;
}

// ── Skills ─────────────────────────────────────────────────────────────────────

/**
 * Declarative metadata for a skill, used in the system prompt and UI lists.
 */
export interface SkillMetadata {
  /** Skill name, e.g. `calendar`. */
  name: string;
  /** One-line description of what the skill does. */
  description: string;
  /** Semantic version of the skill. */
  version: string;
  /** Keywords used for discovery/search. */
  keywords: string[];
  /** Phrases that should activate the skill (system prompt routing hints). */
  triggers: string[];
  /** Path to the SKILL.md file for full instructions (when loaded from disk). */
  skillMdPath?: string;
}

// ── Agent ──────────────────────────────────────────────────────────────────────

/**
 * Everything the agent loop needs to run one turn of a conversation.
 *
 * Built by the app layer from its stores (via `buildAgentContext`) and passed
 * to `agentLoop`.
 */
export interface AgentContext {
  /** Full system prompt (role, skills, memory, tool instructions). */
  systemPrompt: string;
  /** Conversation history, including the new user message. */
  messages: Message[];
  /** Tools available to the model this turn. */
  tools: ToolDefinition[];
  /** Executes a tool by name. The app layer routes to the skill registry. */
  toolExecutor: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  /** Which model tier to run on. */
  modelTier: ModelTier;
  /** Maximum number of model calls before the loop forces a summary. */
  maxSteps: number;
  /** Relevant memories injected from RAG. */
  memories: string[];
  /** Streaming and lifecycle callbacks. */
  callbacks: StreamCallbacks;
  /** Aborts the loop; checked between every step. */
  signal: AbortSignal;
}

/**
 * The outcome of a completed agent loop.
 */
export interface AgentResult {
  /** The model's final answer text. */
  finalAnswer: string;
  /** How many model calls the loop made. */
  steps: number;
  /** Every tool call executed during the loop, in order. */
  toolCalls: ToolCall[];
  /** Cumulative token usage across all steps. */
  usage: { promptTokens: number; completionTokens: number };
}

// ── ExecuTorch bridge ──────────────────────────────────────────────────────────

/**
 * The minimal adapter the react-native-executorch runtime requires.
 *
 * `fetch` downloads (or resolves) resources and returns their local paths;
 * `readAsString` reads configuration files. The full `ResourceFetcher` from
 * `executorch/resource-fetcher` satisfies this shape structurally.
 *
 * The signature mirrors the adapter interface declared by
 * `react-native-executorch/src/utils/ResourceFetcher`.
 */
export interface ResourceFetcherAdapter {
  /**
   * Fetch one or more resources (remote URLs, local paths, or asset ids),
   * reporting overall progress from 0 to 1.
   *
   * @returns The local paths (without `file://` prefix) and, per source,
   *   whether it was downloaded from the network.
   */
  fetch(
    callback: (downloadProgress: number) => void,
    ...sources: (string | number)[]
  ): Promise<{ paths: string[]; wasDownloaded: boolean[] }>;
  /** Read a file at an absolute path as a UTF-8 string. */
  readAsString(path: string): Promise<string>;
}

/**
 * Configuration passed to `initExecutorch`.
 *
 * Registers the resource fetcher adapter so the native ExecuTorch modules can
 * resolve model files, then installs the JSI bindings.
 */
export interface ExecutorchConfig {
  resourceFetcher: ResourceFetcherAdapter;
}
